
import type { PermissionKey } from './types';

export const PERMISSION_KEYS = [
    'view_dashboard',
    'manage_pos',
    'manage_products',
    'view_sales',
    'manage_purchases',
    'manage_customers',
    'manage_suppliers',
    'manage_shipping_companies',
    'manage_partners', 
    'view_treasury',
    'manage_settings',
    'manage_users',
    'manage_backups',
    'view_faq',
    'request_support',
    'manage_sales_returns',
    'manage_purchase_returns',
    'manage_loyalty_program',
    'view_reports',
    'manage_installments',
    'view_system_status',
    'view_activity_logs',
    'view_satisfaction_reports',
    'view_sales_forecast',
    'view_supplier_analysis',
    'view_inactive_customers_report',
    'view_stagnant_products_report',
    'access_admin_tool',
    'manage_notes',
    'manage_whatsapp',
    'manage_ecommerce_api',
    // Advanced Reports
    'view_advanced_reports',
    // HR Permissions
    'manage_hr_attendance',
    'manage_hr_contracts',
    'manage_hr_payroll',
    'manage_hr_requests',
    'manage_hr_personnel',
    // Operations Permissions
    'manage_op_work_orders',
    'manage_op_workflow',
    'manage_op_reservations',
    'manage_op_rentals',
    'manage_op_lease_contracts',
    'manage_op_time_tracking',
    'manage_op_manufacturing',
    // Accounts Permissions
    'manage_acc_chart',
    'manage_acc_expenses',
    'manage_acc_assets',
    'manage_acc_cost_centers',
    'manage_acc_checks',
] as const;

export const PERMISSION_DEFINITIONS: Record<PermissionKey, { name: string; description: string }> = {
    view_dashboard: { name: 'عرض لوحة التحكم الرئيسية', description: 'يسمح للمستخدم بمشاهدة الإحصائيات العامة، الرسوم البيانية للأداء، وقيم المخزون الإجمالية.' },
    manage_pos: { name: 'إدارة نقطة البيع (المبيعات)', description: 'يسمح للمستخدم بفتح شاشة الـ POS، إضافة المنتجات للسلة، وإتمام عمليات البيع واختيار طرق الدفع.' },
    manage_products: { name: 'إدارة المنتجات والمخازن', description: 'يسمح للمستخدم بإضافة منتجات جديدة، تعديل الأسعار، جرد المخزون، والتحويل بين المستودعات.' },
    view_sales: { name: 'عرض سجل المبيعات والفواتير', description: 'يسمح للمستخدم بمشاهدة جميع المبيعات السابقة، طباعة الفواتير، والبحث في أرشيف المبيعات.' },
    manage_purchases: { name: 'إدارة طلبات الشراء والمشتريات', description: 'يسمح للمستخدم بتسجيل مشتريات بضاعة جديدة من الموردين وتحديث رصيد المخزن تلقائياً.' },
    manage_customers: { name: 'إدارة سجلات العملاء والديون', description: 'يسمح للمستخدم بإضافة عملاء جدد، تعديل بياناتهم، ومتابعة مديونيات كل عميل بشكل مستقل.' },
    manage_suppliers: { name: 'إدارة سجلات الموردين وحساباتهم', description: 'يسمح للمستخدم بإدارة بيانات الموردين الذين يتم شراء البضاعة منهم ومتابعة مستحقاتهم المالية.' },
    manage_shipping_companies: { name: 'إدارة شركات الشحن والتوصيل', description: 'يسمح للمستخدم بإضافة وتعديل بيانات شركات الشحن التي يتعامل معها المتجر لتوصيل الطلبات.' },
    manage_partners: { name: 'إدارة الشركاء وتوزيع الأرباح', description: 'صلاحية حساسة تسمح بإدارة نسب الشركاء وحساب أرباحهم المستحقة بناءً على المبيعات والمصاريف.' },
    view_treasury: { name: 'عرض الخزينة والحركات المالية', description: 'يسمح للمستخدم بمتابعة الأرصدة النقدية في الخزائن، والتحويلات المالية، وتسجيل المصاريف اليدوية.' },
    manage_settings: { name: 'إدارة إعدادات المتجر العامة', description: 'يسمح للمستخدم بتغيير اسم المتجر، الرقم الضريبي، العملة، ونسبة ضريبة القيمة المضافة.' },
    manage_users: { name: 'إدارة المستخدمين والأدوار الأمنية', description: 'يسمح للمستخدم بإضافة موظفين جدد، تحديد أدوارهم، وتعديل صلاحيات الوصول لكل دور.' },
    manage_backups: { name: 'إدارة النسخ الاحتياطي للبيانات', description: 'يسمح للمستخدم بتحميل نسخة احتياطية كاملة من قاعدة البيانات أو استعادة بيانات من ملف خارجي.' },
    view_faq: { name: 'عرض الأسئلة الشائعة والدعم', description: 'يسمح للمستخدم بالوصول لمركز المساعدة وقراءة تعليمات استخدام النظام.' },
    request_support: { name: 'طلب الدعم الفني المباشر', description: 'يسمح للمستخدم بالتواصل مع مطوري النظام لطلب المساعدة التقنية أو الإبلاغ عن مشاكل.' },
    manage_sales_returns: { name: 'إدارة مرتجعات المبيعات', description: 'يسمح للمستخدم باستلام البضاعة المرتجعة من العملاء ورد المبالغ المالية وتحديث المخزن.' },
    manage_purchase_returns: { name: 'إدارة مرتجعات المشتريات', description: 'يسمح للمستخدم برد بضاعة للموردين واسترداد قيمتها المالية وتحديث رصيد المخزن.' },
    manage_loyalty_program: { name: 'إدارة برنامج الولاء والمكافآت', description: 'يسمح للمستخدم بضبط قواعد منح النقاط للعملاء واستبدالها بخصومات نقدية.' },
    view_reports: { name: 'عرض التقارير المالية والتحليلية', description: 'يسمح للمستخدم بالوصول لتقارير الربح والخسارة، أداء الموظفين، والتقارير الضريبية المفصلة.' },
    manage_installments: { name: 'إدارة الأقساط والتحصيل', description: 'يسمح للمستخدم بإدارة خطط التقسيط للعملاء، تسجيل الدفعات الشهرية، ومتابعة المتأخرات.' },
    view_system_status: { name: 'عرض حالة النظام والمزامنة', description: 'يسمح للمستخدم بمشاهدة حالة اتصال قاعدة البيانات وسجلات المزامنة التلقائية.' },
    view_activity_logs: { name: 'عرض سجلات النشاط (الرقابة)', description: 'يسمح للمسؤول بمراقبة كل حركة تتم في النظام (من فعل ماذا ومتى) لضمان الشفافية.' },
    view_satisfaction_reports: { name: 'عرض تقارير رضا العملاء', description: 'يسمح للمستخدم بمشاهدة تحليلات تقييمات العملاء للخدمة بعد عمليات البيع.' },
    view_sales_forecast: { name: 'عرض توقعات المبيعات (AI)', description: 'يستخدم الذكاء الاصطناعي للتنبؤ بمبيعات الشهر القادم وتقديم نصائح ترويجية ذكية.' },
    view_supplier_analysis: { name: 'عرض تحليل الموردين (AI)', description: 'يستخدم الذكاء الاصطناعي لتقييم أداء الموردين وترشيح الأفضل للتعامل معه.' },
    view_inactive_customers_report: { name: 'عرض تقرير العملاء الغائبين', description: 'يسمح بمشاهدة العملاء الذين توقفوا عن الشراء لفترة وتوليد رسائل متابعة ذكية لهم.' },
    view_stagnant_products_report: { name: 'عرض تقرير الأصناف الراكدة', description: 'يسمح بمشاهدة المنتجات التي لم تبع منذ فترة طويلة مع اقتراح عروض لتصريفها.' },
    access_admin_tool: { name: 'الوصول لأداة الإدارة المتقدمة', description: 'صلاحية خاصة جداً للمالك والمطور فقط للتحكم في جوانب النظام التقنية العميقة.' },
    manage_notes: { name: 'إدارة الملاحظات والمهام', description: 'يسمح للمستخدم بتدوين ملاحظاته الشخصية، مهام العمل، وقائمة الطلبات بشكل سريع.' },
    manage_whatsapp: { name: 'إدارة ربط الواتساب', description: 'يسمح للمستخدم بربط المتجر بحساب واتساب لمزامنة الرسائل والمحادثات.' },
    manage_ecommerce_api: { name: 'إدارة الربط بمتجر إلكتروني', description: 'يسمح للمستخدم بإعداد وربط المتجر بالمنصات الخارجية عبر API (سلة، زد، وغيرها).' },
    view_advanced_reports: { name: 'عرض التقارير المالية المتقدمة', description: 'يسمح للمستخدم بالوصول لتقارير الأرباح والمصروفات وصافي الدخل بالتفصيل.' },
    manage_hr_attendance: { name: 'الحضور والانصراف', description: 'يسمح للفنيين أو الموظفين بتسجيل وسحب الحضور والانصراف ومراقبة الساعات.' },
    manage_hr_contracts: { name: 'إدارة مسودات العقود', description: 'يسمح بإعداد عقود الموظفين وحفظها والتعديل عليها.' },
    manage_hr_payroll: { name: 'إدارة المرتبات والأجور', description: 'يسمح بحساب وصرف مستحقات الموظفين والعمولات والخصومات.' },
    manage_hr_requests: { name: 'إدارة طلبات الموظفين', description: 'يسمح بمراجعة طلبات الإجازات والسلف والساعات الإضافية للموظفين والموافقة عليها.' },
    manage_hr_personnel: { name: 'شؤون الموظفين العامة', description: 'إدارة بيانات الموظفين، تقييماتهم، وتوثيق سجلهم الوظيفي.' },
    manage_op_work_orders: { name: 'إدارة أوامر الشغل', description: 'يسمح بإنشاء وصيانة وتتبع أوامر العمل الداخلية والخارجية.' },
    manage_op_workflow: { name: 'دورة العمل (العمليات)', description: 'يسمح بالمتابعة الشاملة لتدفق العمل وتحديث حالة مراحل التشغيل.' },
    manage_op_reservations: { name: 'إدارة الحجوزات والمواعيد', description: 'يسمح بحجز وجدولة المواعيد مع العملاء وإدارة التقويم.' },
    manage_op_rentals: { name: 'إدارة الإيجارات والوحدات', description: 'يسمح بالتحكم في الوحدات المؤجرة، متابعة المستأجرين والصيانة.' },
    manage_op_lease_contracts: { name: 'إدارة عقود الإيجار', description: 'توليد عقود الإيجار للوحدات المتاحة وحفظها وجدولتها.' },
    manage_op_time_tracking: { name: 'تتبع الوقت والتكاليف', description: 'يسمح بتتبع الوقت المستغرق في تنفيذ العمل لمعرفة التكاليف الإضافية.' },
    manage_op_manufacturing: { name: 'إدارة التصنيع والإنتاج', description: 'يسمح بمتابعة المواد الخام وخطوط الإنتاج والتصنيع المحلي.' },
    manage_acc_chart: { name: 'دليل الحسابات المالي', description: 'إضافة وتعديل الحسابات وتصنيفها كشجرة حسابات معتمدة.' },
    manage_acc_expenses: { name: 'إدارة ومراقبة المصروفات', description: 'تسجيل وتبويب وتتبع جميع المصروفات العمومية والتشغيلية.' },
    manage_acc_assets: { name: 'إدارة الأصول الثابتة', description: 'تسجيل أصول المنشأة واحتساب الإهلاك الدوري وإدارة جردها.' },
    manage_acc_cost_centers: { name: 'إدارة مراكز التكلفة', description: 'تخطيط وتقسيم النفقات والايرادات على مراكز تكلفة منفصلة للتقييم.' },
    manage_acc_checks: { name: 'دورة الشيكات والسندات', description: 'إدارة الشيكات المستلمة والصادرة للعملاء والموردين وتتبع التواريخ ومواعيد الصرف.' },
};
